const path=require("path")
const ExtractTextPlugin=require(require.resolve("extract-text-webpack-plugin"));

module.exports={
	rules:[{
		test:/\.scss$/,
        use:ExtractTextPlugin.extract({
            use:[{loader:"css-loader?module&localIdentName=[local]-[hash:base64]"},{loader:"sass-loader"}],
            fallback:"style-loader",
        })
	},{
		test:/\.css$/,
        use:ExtractTextPlugin.extract({
            use:{loader:"css-loader"},
            fallback:"style-loader",
        })
    },{
		test:/\.(js|jsx)$/,
		use:[{loader:"babel-loader"}],
		exclude:/node_modules/,
	},{
		test:/\.(otf|eot|svg|ttf|woff|woff2)$/,
        use:[{
            loader:"file-loader",
            options:{
            	name:"myFiles-[name].[ext]",
            	outputPath:"./fonts/",
            	publicPath:"./"
            }  
        }]
	},{
		test:/\.(png|jpg|jpeg|gif)$/,
        use:[{
            loader:"file-loader",
            options:{
            	name:"myFiles-[name].[ext]",
            	outputPath:"images/",
            	publicPath:"./",
            }  
        }]
	},{
		test:/\.json$/,
		use:["json-loader"]
	},{
		test:/\.(html|htm)$/,
		use:[{loader:"html-loader"}]
	}]
}